# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filtre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coincidencia', models.CharField(max_length=2000)),
                ('tipus', models.CharField(max_length=20)),
                ('pagina', models.IntegerField()),
                ('url', models.URLField(max_length=2000)),
                ('data', models.DateTimeField(verbose_name="Data de l'avís")),
            ],
            options={
                'verbose_name': 'avís',
                'verbose_name_plural': 'avisos',
            },
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='font',
        ),
        migrations.RemoveField(
            model_name='font',
            name='haserror',
        ),
        migrations.RemoveField(
            model_name='font',
            name='path',
        ),
        migrations.AddField(
            model_name='font',
            name='webfile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
        migrations.AddField(
            model_name='avis',
            name='font',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filtre.Font'),
        ),
    ]
