# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtre', '0003_auto_20160420_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='pagina',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cataleg',
            name='fonts',
            field=models.ManyToManyField(null=True, to='filtre.Font'),
        ),
    ]
