# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtre', '0004_auto_20160420_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cataleg',
            name='fonts',
            field=models.ManyToManyField(to='filtre.Font'),
        ),
    ]
