# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtre', '0005_auto_20160420_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='webfile',
            field=models.FileField(blank=True, default=None, null=True, upload_to='filtre.WebFileModel/dades/nom/mimetype'),
        ),
    ]
