# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtre', '0007_auto_20160523_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='catalegs',
            field=models.ManyToManyField(blank=True, to='filtre.Cataleg'),
        ),
        migrations.AlterField(
            model_name='cataleg',
            name='fonts',
            field=models.ManyToManyField(blank=True, to='filtre.Font'),
        ),
    ]
