# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtre', '0008_auto_20160610_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data de l'avís"),
        ),
    ]
